# Generated by Django 6.1.1 on 2026-10-06 23:30

import builtins
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
                ('lugar_nacimiento', models.CharField()),
                ('fecha_nacimiento', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='libro',
            fields=[
                ('titulo', models.CharField()),
                ('descripcion', models.TextField()),
                ('autor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=builtins.id, serialize=False, to='biblioteca.autor')),
            ],
        ),
    ]
